name: Bug Report
description: Report a bug in Aratta
labels: ["bug"]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for reporting a bug. Please fill out the sections below.
  - type: textarea
    id: description
    attributes:
      label: Description
      description: What happened?
      placeholder: A clear description of the bug.
    validations:
      required: true
  - type: textarea
    id: expected
    attributes:
      label: Expected Behavior
      description: What did you expect to happen?
    validations:
      required: true
  - type: textarea
    id: reproduce
    attributes:
      label: Steps to Reproduce
      description: Minimal steps to reproduce the issue.
      placeholder: |
        1. Run `aratta serve`
        2. Send a request to ...
        3. See error ...
    validations:
      required: true
  - type: input
    id: version
    attributes:
      label: Aratta Version
      placeholder: "0.1.0"
    validations:
      required: true
  - type: input
    id: python-version
    attributes:
      label: Python Version
      placeholder: "3.11.8"
    validations:
      required: true
  - type: input
    id: os
    attributes:
      label: Operating System
      placeholder: "Ubuntu 22.04 / Windows 11 / macOS 14"
    validations:
      required: true
  - type: textarea
    id: logs
    attributes:
      label: Relevant Logs
      description: Paste any error output or stack traces.
      render: shell
